### ISSUE TITLE
 limit concurrency of `Docker build` workflow to one

### ISSUE THREAD

**Issue by p0lygun** [battlefield-portal-community/bfportal.gg#127]
```yml
concurrency:
  group: ${{ github.head_ref || github.ref_name }} 
  cancel-in-progress: true
```
